### PR TITLE
Mini timer design update

### LINKED ISSUE #2009: Make the size of the mini-timer less.
Hello. Please make the size of the mini timer is less, it is too big! Or, provide the opportunity to make it smaller (I use: Windows Desktop Toggle App). Thank you!

### LINKED ISSUE #3486: Mini timer design update
### 💻 Environment
Platform: Windows

### 📒 Description
Implement Mini timer view according to the new design.
Currently Mini timer shares the view code with the main window timer, in the new design the timers look different so their view code should be separated.

### PR DESCRIPTION
**Pull request by skel35**
### 📒 Description
Implementation of the new design of the mini timer.

### 🕶️ Types of changes
- **Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes
 - [x] Updated design for the Mini timer
 - [x] Moved Mini timer window from custom `ChromelessWindow` to library's `MetroWindow`
- [x] Removed low-level resizing hack in favor of simple property setter
- [x] Extracted a few user controls that are shared between the timer and the mini timer

### 👫 Relationships
Closes #3486
Closes #2009

### 🔎 Review hints
- Verify that the mini timer design matches the one specified in Zeplin
- Test the mini timer functionality to make sure everything works

Existing issues:
- Mini timer loses keyboard focus when starting time entry. This issue exists on `master` as well. To be fixed in #3725.
- There's still a bit of code duplication between timer and mini timer. Previously the mini timer UI was identical to timer, so they used exact same user control. Now they have several differences. As there was no separation between UI layout and UI logic, it will take a lot of time to properly get rid of code duplication. Created #3730 to fix this issue.

### CODE REVIEW

**Comment by skel35** [comment]
Thanks for review @NghiaTranUIT !
Regarding the second point: the height of the mini timer should be bigger when selecting from autocomplete view, otherwise TextBox + project bar won't fit. This is corresponding to the Zeplin design, please check out this mockup from Zeplin:
image
Regarding the first point, you're right, it should be square on the first screenshot, I'll have a look into it.

**Comment by NghiaTranUIT** [comment]
Understand the size of the mini bar, but I suggest that we should make sure the Red Box is square (width=height) 😄

**Comment by skel35** [comment]
To me personally, it looks ok with height>width if it's only in a scenario when we have a project bar.
Please offer your suggestion in #project-win-redesign or in Zeplin. If the designer agrees with you I'd be happy to always keep it square 😄

**Comment by skel35** [comment]
Fixed the issue with increased height in the running state. 
@NghiaTranUIT Ready for re-review.

**Pull request merged**
