### PR TITLE
Get rid of everything that got printed to stderr in Linux

### LINKED ISSUE #4510: Annoying debug messages get printed to stderr after start
### 💻 Environment
Platform: Linux
Toggl Version: 7.5.303

### 🐞 Actual behavior
```
QDBusMessage(type=MethodReturn, service=":1.18", signature="h", contents=([Unix FD: valid]) ) ""
QObject::connect: No such signal TogglApi::setProjectColors(QVector<char*>) in /home/mbriza/code/toggldesktop/src/ui/linux/TogglDesktop/timeentryeditorwidget.cpp:82
QObject::connect:  (receiver name: 'TimeEntryEditorWidget')
QStackedWidget::setCurrentWidget: widget 0x30 not contained in stack
```

### 💯 Expected behavior
```

```

### 🔨 Steps to reproduce
1. Run the app

### 📦 Additional info
`QDBusMessage` is coming, well, from some DBus call

`connect` is a function signature change

`setCurrentWidget` is coming from a wrong stack initialization

All are benign and pretty easy to fix, it's worth doing it because they tend to confuse users when debugging an issue.

### PR DESCRIPTION
**Pull request by MartinBriza**
### 🕶️ Types of changes
- **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- There should be no more clutter in the terminal output

### 👫 Relationships
Closes #4510 

### 🔎 Review hints
Everything should work the same as before except for the messages that get printed to the terminal.

### CODE REVIEW

**Review by skel35 — APPROVED** [review]
I still get one error message in a few seconds after app start:
>QDBusError("org.freedesktop.DBus.Error.NotSupported", "This method is not implemented")

Looks good otherwise.

**Comment by MartinBriza** [comment]
Now even your warning shouldn't be present.

**Comment by MartinBriza** [comment]
For the record, the build failure is caused by this: 
```
W: Failed to fetch https://apt.kitware.com/ubuntu/dists/xenial/InRelease  Connection timed out after 120001 milliseconds
```
Not by the commit I pushed - seems the repo we're getting a newer CMake from is down at this moment (hopefully will be up soon)

**Review by skel35 — APPROVED** [review]
looks good

**Pull request merged**
