### PR TITLE
macOS app rebranding

### LINKED ISSUE #4295: Idle time popup needs better contrast for the Green button in dark mode
### 💻 Environment

Platform: macOS

### 📒 Description

The green button has white text in dark mode, and it's not super easy to read. 
image

### ⭐️ Why do you want this?

To make it easier for users to see the text.

### LINKED ISSUE #4301: Update colors and icons in the macOS app
### 💻 Environment
Platform: macOS

### 📒 Description
Update colors and icons in the macOS app according to the upcoming rebranding.

Designs:
https://toggl.invisionapp.com/d/main#/projects/prototypes/20343116
Higher-res icons for the dock:
[MacOS–Icons.zip](https://github.com/toggl-open-source/toggldesktop/files/5041545/MacOS.Icons.zip)

Note: Should not be included in the public release until September 7th.

### PR DESCRIPTION
**Pull request by skel35**
### 📒 Description
TBD

### 🕶️ Types of changes
- **Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes

TBD

### 👫 Relationships
Closes #4301
Closes #4295

### 🔎 Review hints
TBD

### CODE REVIEW

**Comment by AndrewVebster** [comment]
Ready for review.
Also waiting for feedback from Milad, so maybe will need to update something later.

**Comment by AndrewVebster** [comment]
Changed to WIP. Received change requests from Milad

**Comment by MartinBriza** [comment]
I found some issues in the current version:
* The app logo in the dmg package is off (dark), it should be on (light)
* In the idle notification, the top selected choice looks disabled (gray text) in both light and dark mode
image
* Idle notification buttons don't have borders in light mode, I'm not sure if that's actually an issue though
image

**Comment by AndrewVebster** [comment]
Fixed Idle notification and other issues I was telling you before.
Haven't yet looked into app logo in dmg.

**Comment by AndrewVebster** [comment]
About

> The app logo in the dmg package is off (dark), it should be on (light)

We're using [create-dmg](https://github.com/sindresorhus/create-dmg) tool to generate dmg and it doesn't allow to change app logo there.

**Comment by MartinBriza** [comment]
Well, I suppose that also means the default app logo (that will get displayed in the application menu) is dark, not just the one in the dmg. That would mean the default app logo should be changed, right?

**Comment by AndrewVebster** [comment]
We have "running" (pink) and "not-running" (dark) app icons. The default is "not-running", like it was before.
I didn't think we should change this behavior.

**Review by MartinBriza — APPROVED** [review]
This must`ve been stressful but now I feel it`s done! Or if there`s anything else left to change, it`ll be pretty minor. Great job, Andrii!

**Pull request merged**
