### PR TITLE
Refactor colors on macOS

### LINKED ISSUE #4747: Refactor colors in macOS app
### 💻 Environment

Platform: macOS

### 📒 Description

Improve how we use colors on macOS. 
Add linters to raise warnings when colors are hardcoded. 
Remove hardcoded colors

### PR DESCRIPTION
**Pull request by AndrewVebster**
### 📒 Description

This PR refactors colors on macOS app. 
- Added two linters
- Introduced new Color type instead of system one
- Removed 21 hardcoded colors from code (50 left)

### 🕶️ Types of changes

- **Breaking change** (fix or feature that would cause existing functionality to change)

### 👫 Relationships

Closes #4747

### CODE REVIEW

**Review by skel35 — COMMENTED** [review]
Looks good! You just forgot to fix those SwiftLint warnings.

**Comment by AndrewVebster** [comment]
Don't know why swiftlint post the comment if `Colors.swift` file is in the ignore list. It works fine locally...

**Comment by skel35** [comment]
how do you run this locally?
P.S. now the conflicts have to be resolved too

**Review by skel35 — APPROVED** [review]
No errors now.

**Pull request merged**
