### PR TITLE
Remove all Lua reference 

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR will completely remove all lua reference in all platforms and the Script for UI testing.

### ⚠️ Warning
Please make sure we merge #3809 firstly since this PR is branched off.

### 🕶️ Types of changes
**Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes
- [x] Remove all lua reference and code in all platforms
- [x] Remove Console and Run script in library and all platforms

### 👫 Relationships
Closes #3809

### 🔎 Review hints
Verify that:
- Able to build and run TogglDesktop in macOS, Window and Linux

### CODE REVIEW

**Comment by skel35** [comment]
@NghiaTranUIT The build is failing in GH Actions, could you please fix it?

**Comment by NghiaTranUIT** [comment]
Fixed. Waiting the GA 👍

**Comment by skel35** [comment]
@NghiaTranUIT can you please rebase this branch to resolve the conflicts?

**Comment by NghiaTranUIT** [comment]
- Merged from parent because the parent changed a lot project structure.
- Verify the DEV and PROD build are meet the Acceptance Criteria 
All done 🙌

**Pull request merged**
