### PR TITLE
Update yaml to upload win64 installer as artifact

### LINKED ISSUE #3552: Create and upload app installers as artifacts in GitHub Actions branch builds
### 💻 Environment
Platform: Windows

### 📒 Description
Currently only `master` builds produce installers that are getting uploaded to GitHub Releases. For branch builds we should not upload installer to GitHub Releases, but saving them as [artifacts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts) makes sense. 
The version should be set to `7.0.0` so that it looks like our local builds.

This would be very useful for testing purposes both within our team, as the tester would not need to build an app locally, and outside our team if we want someone else to try out the branch build (this will be needed quite a few times during Windows new UI development).

### PR DESCRIPTION
**Pull request by atsvirchkova**
### 📒 Description
Update yaml to upload win64 installer as artifact

### 🕶️ Types of changes

- **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
main.yml

### 👫 Relationships

 Closes #3552

### CODE REVIEW

**Comment by atsvirchkova** [comment]
1. You're right. It's a bit too early to review it, I'm now fixing this. And also I plan to fix that we don't need artifacts for release builds.
2. Will remove that, of course.
3. So, can I remove the install NSIS step at all? I mean for release config also.

**Comment by skel35** [comment]
@atsvirchkova OK, I'm sorry for commenting too early on this. Next time please create a "Draft Pull Request" next time or add "[WIP]" in the title so that we know it doesn't need to be reviewed yet :)
Regarding 3 yes, as the build agents already have NSIS installed we can save build time by removing the "install NSIS" step.

**Comment by atsvirchkova** [comment]
@skel35 OK, sorry for disturbing you too early. Next time I'll do a draft pull request.

**Comment by atsvirchkova** [comment]
Created issues #4219 and #4220 for macOs and linux artifacts.

**Pull request merged**
