### PR TITLE
Main view markup (Timeline UI)

### LINKED ISSUE #4354: Main view markup (Timeline UI)
### 💻 Environment

Platform: Windows

### 📒 Description
split the main view into 3 blocks (time, time entries, activity)
add time marks for time blocks + make every other hour darker

### PR DESCRIPTION
**Pull request by atsvirchkova**
### 📒 Description
split the main view into 3 blocks (time, time entries, activity)
add time marks for time blocks + make every other hour darker

### 🕶️ Types of changes

- **New feature** (non-breaking change which adds functionality)

### 👫 Relationships

 Closes #4354

### CODE REVIEW

**Review by skel35 — CHANGES_REQUESTED** [review]
Looks great, I have just 2 small comments:

1. The header should be visible at all times when scrolled downwards, like in the macOS app. Otherwise, this is a bad UX. Even the scrolling behavior from the designs (where header gets hidden but reappears when scrolling upwards) is a bit questionable for a desktop app, looks more suited to the mobile app IMHO.
2. Let's just use `Toggl.SecondaryTextBrush` and do not introduce the new `Toggl.TimelineTimeColor`, to simplify things. The designer could've made a mistake there, or just took the colors from elsewhere, but SecondaryTextBrush looks good here as well.

**Comment by atsvirchkova** [comment]
I have a question about headers. I now looked into designs and it says, that the headers really must be always visible, I missed it. But it also says, that the area with date picker must scroll. In macOS, the date picker always stays on top, so as headers. So may I use the macOS solution for this?
Making so that date picker would scroll and the headers would not is non-trivial.

**Comment by skel35** [comment]
Yes, please use the macOS solution here.

**Comment by atsvirchkova** [comment]
Fixed the headers and removed unnecessary colors. Ready for review.

**Review by skel35 — CHANGES_REQUESTED** [review]
The previously mentioned issues are fixed, but I've noticed one more - scrolling over the empty state textblocks isn't working:
5YYDAGWNsp

**Comment by atsvirchkova** [comment]
Good finding. Thank you. Fixed now.

**Review by skel35 — APPROVED** [review]
Looks good 👍

**Pull request merged**
