### PR TITLE
Add logging on/off parameter to TogglClient

### LINKED ISSUE #4578: Exclude analytics requests details from the log files
### 💻 Environment

Platform: All Platforms

### 📒 Description
All requests to Google analytics are now logged, which immediately fills in the log files. We don't want to have them in logs as it makes hard to extract any other valuable information from there.

### PR DESCRIPTION
**Pull request by atsvirchkova**
### 📒 Description
At the moment we log all http requests, and this logging is built in `makeHttpRequest` method. These changes add a boolean parameter which indicates if logging is needed. 

### 🕶️ Types of changes

- **Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes
analytics.cc
http_client.h
http_client.cc

### 👫 Relationships

 Closes #4578 

### 🔎 Review hints
How to test: 
- Run the app in release mode.
- Open the log files.
- Check that there is not `google.analytics` requests there.

### CODE REVIEW

**Review by skel35 — CHANGES_REQUESTED** [review]
This works fine, but let's improve the PR even more.
All the `silentGet` calls are the not-so-important calls (not related to syncing or the business logic), so we can remove logging from all of them. By doing that we would avoid an unnecessary boolean parameter in the `silentGet` method.

**Comment by atsvirchkova** [comment]
@skel35 OK, that sounds reasonable. I'll remove the parameter from `silentGet`, but it will still remain in `request` and `makeHttpRequest` methods.

**Comment by atsvirchkova** [comment]
Fixed, now ready for review again.

**Review by skel35 — APPROVED** [review]
logs are now cleaner for sure 👍 
looks good

**Pull request merged**
