### PR TITLE
InAppMessage improvement

### LINKED ISSUE #3587: Add analytics to in-app button clicks
### 💻 Environment
Platform: macOS/Windows

### 📒 Description
When user clicks on an action in the in-app message we should track it.

- Click on close button should trigger `toggl_iam_click(ctx, 2)`
- Click on the bottom button should trigger `toggl_iam_click(ctx, 3)`

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR add some logic to make sure InAppMessage call some lib func

### 🕶️ Types of changes
**Improvement** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Add missing headers in library
- [x] Call proper lib funcs when clicking buttons in InApp Message

### 👫 Relationships
Closes #3587

### 🔎 Review hints
- Make sure it executes the APIs correctly 👍

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
Checking linux failed ❌

**Comment by IndrekV** [comment]
Did some small fixes. As close button action was called to animate view close also the analytic cal for close was triggered for action button.

**Comment by IndrekV** [comment]
This looks good to merge. Let's wait for the checks and then we are good to go.

**Comment by NghiaTranUIT** [comment]
Thank for point it out. My mistake 💥

**Comment by MartinBriza** [comment]
The Linux checks "failing" is the test suite literally crashing completely, that shouldn't happen. I'll fix this so it doesn't bail on us when the test suite itself crashes.

**Pull request merged**
