### PR TITLE
Change appcast url from assets.toggl.com to github pages

### LINKED ISSUE #1611: Move appcast files to github
- [x] Move appcast files to github
- [ ] Change the appcast url inside the app
- [ ] Use the raw url to fetch Appcast

### PR DESCRIPTION
**Pull request by skel35**
### 📒 Description
Change appcast url from assets.toggl.com to github pages

### 🕶️ Types of changes
- **Breaking change** (fix or feature that would cause existing functionality to change)

### 👫 Relationships
Closes #1611

### 🔎 Review hints
Build a release version of the app with an older version number and make sure it can update itself. Verify the update works on all 3 channels: stable, beta, dev.

### CODE REVIEW

**Comment by skel35** [comment]
@NghiaTranUIT I've just realized we don't even need to set up redirects from assets.toggl.com links. If the assets.toggl.com link gets outdated, but still links to the newer Toggl Desktop version that will itself contain a link to github, the updates will go well.
E.g. let's say we changed the appcast link to github in 7.5.60 stable and release a new version 7.5.70 stable after that. On assets, we keep the link to 7.5.60.
Then the users on an older version, let's say 7.5.16, will be able to update to 7.5.60 using assets link and while on 7.5.60 will then receive an update to 7.5.70 using github link.

**Comment by skel35** [comment]
So after merging this PR, we need to update an appcast files on assets.toggl.com only for the next stable release. After that, we can drop it and upload new appcast only to github.

**Comment by NghiaTranUIT** [comment]
Yup, I had the same thought too, but it means all TogglDesktop users' (roughly 100k) have to update twice (waste x2 the user time) in order to. get the latest build. Ultimately, I still prefer an approach to less impact on the end-users.

Don't worry, we could request a hand from BE team to redirect the link properly.

**Comment by NghiaTranUIT** [comment]
Tested and all working.
Waiting GA to release a DEV and update a appcast file and testing again 👍

**Comment by NghiaTranUIT** [comment]
Tested some major scenarios:
- I archive a production build from this branch (with lower version: 7.5.50), and I'm able to update to DEV 7.5.69 (Lasted build from GA)
- AppCasts (dev, beta, prod) are correct.

Finally, the PR is working as expected 🙌 

--------------

Regarding https://github.com/toggl-open-source/toggldesktop/pull/3856#issuecomment-591846151

We could release a DEV build from Minibot again to make sure the AppCast (in Mini-bot) has a latest builds, which has the change of AppCast URL

**Comment by skel35** [comment]
@NghiaTranUIT If this PR is working fine, then it's better to merge it early because we'll have to update the appcast files on assets.toggl.com _after_ the PR is merged and new versions are released.

**Comment by NghiaTranUIT** [comment]
When GA action finish to release a DEV build. I'm going to release a DEV build again by Mini Bot. Therefore, the assets are updated to the new build too 👍

**Pull request merged**
