### PR TITLE
Implement Time entry list UI

### LINKED ISSUE #3694: Time entry list design update
### 💻 Environment
Platform: Windows

### 📒 Description
Time entry list design update. Will probably need to be split into a few tasks.

### PR DESCRIPTION
**Pull request by skel35**
### 📒 Description
Implementation of the entire Time entry list UI according to the design update.

### 🕶️ Types of changes
- **Breaking change** (fix or feature that would cause existing functionality to change)

#### Visual
- [x] New design of Time entry cell, Day header, Load more button
- [x] Introduce [acrylic](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic) window background (shown on Windows 10 1803+)
- [x] Margin between days, shadows from days and from the timer
- [x] Titlebar receives active view's background
#### Behavior
- [x] Timer is now receiving focus whenever the timer view is activated
- [x] Timer description textbox is now receiving focus if the time entry is stopped while the timer is focused
- [x] Titlebar and start/stop button are no longer focusable
- [x] First entry from the list now receives focus immediately after pressing Shift-Down from the timer.
#### Code quality
- [x] Highlight and selection logic implementation is now based on WPF's keyboard focus and is using the MVVM pattern.
- [x] Introduced TimeEntryCellViewModel, DayHeaderViewModel, TimeEntryLabelViewModel, ProjectLabelViewModel for better separation of presentation and logic.
 
### 👫 Relationships
Closes #3694

### 🔎 Review hints
Verify the design matches Zeplin, check Light and Dark mode.
Almost the entire Time entry list view was reimplemented, so everything in it should be checked:
- Scrolling days/entries
- Opening edit view by click (the corresponding field should get focus)
- Expanding/collapsing days by click
- Expanding/collapsing group entries by click
- Navigation between entries using a keyboard
- Expanding/collapsing days using a keyboard
- Expanding/collapsing group entries using a keyboard
- Expand/collapse all days using context menu and using a shortcut
- Verify that timer still works
- Verify that mini timer still works
- Try to find some other bugs that could've been introduced

Note: The rendering issue with a maximized window will be fixed in a separate ticket #3770.

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
@skel35 Please rebase and resolve the conflict of this PR, I would like to review it 🙌

**Comment by skel35** [comment]
@NghiaTranUIT Thanks for pointing it out! Rebase is done, ready for review.

**Comment by NghiaTranUIT** [comment]
5. I'm not sure what is wrong with the Debug build, but I couldn't save any Entry (Red icon), even though I logout, clear cache and login again.
Screen Shot 2020-02-07 at 20 46 38

**Comment by skel35** [comment]
@NghiaTranUIT 
Thanks for the feedback!
Answers to your points:

1,2: We're going to have a small red scrollbar everywhere it's needed in our app. It will be implemented separately #3487.
3. Expanding the autocompletion popup was an intention, but you're right that it looks weird. We can make the Width fixed. I've created a separate ticket #3797 for this as it wasn't touched in the Time Entry List UI ticket.
4. Acrylic is only compatible with Windows 10 1803+. I'm enabling Acrylic only for these Windows versions, otherwise it's just a semi-transparent background without any blurring. We will test the app on Windows 7 before releasing it to make sure it works there. For now, it's enough to test it on Windows 10.
5. I suspect it was a backend issue with Staging as I do not encounter any issues now.

**Comment by NghiaTranUIT** [comment]
Thank for the detail explanation @skel35. I'm happy with this PR 👍

**Pull request merged**
