### PR TITLE
[Do Not Merge] Pre-populate Timeline data for Testing users

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR will reload the the timeline_events at the first launch for testing users.

### 🤯 List of changes
- [x] Add dataset
- [x] Import to local database

### Datasheet
PM @NghiaTranUIT on slack for the link

### How to release new Timeline with pre-populated data
This branch includes all code for importing the timeline_event in the first launch. The following is steps what how we release for users
1. Rebase or merge from `feature/timeline-ui` to get new code
2. Go to mini-bot, check out this branch, open Xcode
3. Project -> Archive and export the build.
4. Send to beta-users

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
## Timeline - Update 1
- Don’t import the dataset at the first launch. We have to manually do it by Help menu -> Import.
- Auto replace the current UID to timeline_events
- Show an alert to notify the user to re-open the app.
- Better timeline activity dataset

[TogglDesktop.zip](https://github.com/toggl/toggldesktop/files/3642405/TogglDesktop.zip)

**Comment by NghiaTranUIT** [comment]
## Timeline - Update 2
- Updated from the latest macOS Stable 7.4.1012
- Fixed: Lost focus on TimeEntry Editor in Timeline 
- Fixed: Incorrect size of AutoComplete View

[TogglDesktop-Timeline-v2.zip](https://github.com/toggl/toggldesktop/files/3661862/TogglDesktop-Timeline-v2.zip)

**Comment by NghiaTranUIT** [comment]
## Update 3
- Update from the latest stable 7.4.1023 version
- UI improvement (https://github.com/toggl/toggldesktop/issues/3380)

[TogglDesktop.zip](https://github.com/toggl/toggldesktop/files/3694643/TogglDesktop.zip)

**Comment by NghiaTranUIT** [comment]
## Update 4
- Finished UI Improvement (#3380) (Fix the vertical center of the empty label)

[TogglDesktop.zip](https://github.com/toggl/toggldesktop/files/3695628/TogglDesktop.zip)

**Comment by skel35** [comment]
I suppose we don't need this anymore since the Timeline feature was released months ago

**Pull request closed without merging**
