### PR TITLE
Pre-compile library for mac TogglDesktop

### LINKED ISSUE #3804: Pre-compile Poco and OpenSSL for macOS
## Description
`make deps` is a time-consuming task in mini-bot and Github Action, we should get rid of it someway to reduce the build time.

## 💻 Environment
macOS

## Acceptance Criteria 
- Find the way to pre-compile Poco and OpenSSL libraries
- Embed to DesktopLibrary

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR will add Pre-compile some Libraries, which are required for macOS build, such as Poco, OpenSSL, Lua, jsoncpp.

### Pros
- Build the macOS TogglDesktop straight from the source, no need `make deps`
- Increase build time on Mini-Bot and Github Action

### Cons
- Increase macOS Codebase size to 19.7Mb

### 🕶️ Types of changes
**Breaking change** (fix or feature that would cause existing functionality to change)

### How it implement
- Add all pre-compile (a, dylib) (Poco, OpenSSL, lua, jsoncpp) to Library Folder at `ui/osx/TogglDesktop/Library`
- Add all headers (include) to the Library Folder
- Update Header Search Path and Library Search Path to correspond with new home
- Change .gitignore to not skip those files

### 👫 Relationships
Closes #3804

#### Able to build and run
1. Complete wipe out the project (Project -> Clean and remove caching in DerivedData) or freshly checkout this branch
2. `git reset --hard && git clean -fdx`
3. `make init_cocoapod`
4. Remove all poco and openssl libs in users
```
/usr/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
/usr/local/lib/libPocoJSON.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libPocoCrypto.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
/usr/local/lib/libPocoDataSQLite.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libPocoUtil.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libPocoNet.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libPocoData.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libPocoFoundation.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libPocoNetSSL.60.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/local/lib/libPocoXML.60.dylib (compatibility version 0.0.0, current version 0.0.0)
```
5. Open TogglDesktop.workspace and build, verify:
- Able to build and run all schemes 
- No crash at launch time
6. Try to archive, verify:
- Able to build and run all schemes
- No crash at launch time

#### Try build on 10.14
Download two production build 
- Non AppStore build: https://www.dropbox.com/s/t8on3vu8vf4zmsu/TogglDesktop-Production%202020-02-24%2017-32-25.zip?dl=0
- AppStore build https://www.dropbox.com/s/cwxv5n9zfelzvdx/TogglDesktop-AppStore-Production%202020-02-24%2017-42-10.zip?dl=0
Verify that:
- Able to run two builds in your machine
- Able to run two build in macOS 10.14 (Virtual machine, not a dev machine)

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
- [ ] Investigate the crash on Production build (After archiving from this branch)

**Comment by NghiaTranUIT** [comment]
All done. Ready to review 👍

**Comment by NghiaTranUIT** [comment]
Resolved the conflict 👍 but please postpone this ticket until we release a new BETA Timeline build in this week 🤚

**Comment by skel35** [comment]
@NghiaTranUIT 
I'm getting a crash at startup with the following output:
> dyld: Library not loaded: /usr/local/lib/libcrypto.1.1.dylib
>  Referenced from: /Users/t/Library/Developer/Xcode/DerivedData/TogglDesktop-dgeoxrnmxtuahudcublzjoamtjfb/Build/Products/Debug/TogglDesktop.app/Contents/MacOS/TogglDesktop
  Reason: image not found
(lldb) 

I had cloned the repo from scratch, cleaned the DerivedData folder manually, cleaned build folder from Xcode, ran `make init_cocoapod` and built `TogglDesktop` target from Xcode.

**Comment by NghiaTranUIT** [comment]
Please don't review this PR until I resolve the invalid dynamic linking of the app 🤚

**Comment by NghiaTranUIT** [comment]
## Changelog
- Fix the dynamic linking from TogglDesktop (Normal and AppStore scheme). In the past, on debugging build, it seek the Poco libs from /usr/local/lib/.

**Comment by NghiaTranUIT** [comment]
It's ready to review @skel35 🤚 

If the PR is approved, please don't merge to the master yet, since it's a huge change and I would to ship the Timeline before 👍

**Comment by skel35** [comment]
I've tested everything on Catalina, works well, except for archiving. I have never done this before myself, so I'm probably doing it wrong, but what I did was: 
- switch to `TogglDesktop-Production`
- Product->Archive
- Distribute App->Copy App
- Try to run the copied app
=> The app didn't start

**Comment by NghiaTranUIT** [comment]
Waiting the GA finishes and then we can merge this PR to master 👍

**Pull request merged**
