### PR TITLE
Linux: Fix google login browser + Update packaging

### LINKED ISSUE #4098: Segfault in libQt5WebEngineCore in Flatpak, on Fedora
### 💻 Environment
Platform: Linux
OS Version: Fedora 32
Toggl Version: 7.4.528

Other fun things:
* Kernel 5.6.13
* Gnome 3.36.2
* X11 1.20.8
* NVidia driver 440.82
* Flatpak 1.6.3

Flatpak-ery:
```
$ flatpak list
Name                               Application ID                                            Version        Branch      Installation
TogglDesktop                       com.toggl.TogglDesktop                                                   stable      system
default                            org.freedesktop.Platform.GL.default                                      19.08       system
nvidia-440-82                      org.freedesktop.Platform.GL.nvidia-440-82                                1.4         system
html5-codecs                       org.freedesktop.Platform.html5-codecs                                    18.08       system
openh264                           org.freedesktop.Platform.openh264                                        2.0         system
Freedesktop SDK                    org.freedesktop.Sdk                                       19.08.10       19.08       system
Adwaita theme                      org.kde.KStyle.Adwaita                                                   5.12        system
KDE Application Platform           org.kde.Platform                                                         5.12        system
QGnomePlatform                     org.kde.PlatformTheme.QGnomePlatform                                     5.12        system
KDE Software Development Kit       org.kde.Sdk                                                              5.12        system
QGnomePlatform-decoration          org.kde.WaylandDecoration.QGnomePlatform-decoration                      5.12        system

```

### 🐞 Actual behavior
When logging in using Google, after inputting my password, if I click next, the application segfaults.

### 💯 Expected behavior
I expect to progress to the 2fa Google screen.

### 🔨 Steps to reproduce
1. Install TogglDesktop using the flatpakref available on the website:
```
$ flatpak install Downloads/com.toggl.TogglDesktop.flatpakref
```
2. Run TogglDesktop via FlatPak
3. Select "Log in with Google Account" — the window opens successfully.
4. Enter your email and click "Next"
5. Enter your password and click "Next" — the google "Something is happening" blue bar at the top is moving fine.
6. Presumably on response coming back, the application Segfaults.

### 📦 Additional info
I'm fairly certain this just has to do with the version of qt webengine. If I install the KDE SDK in Flatpak, I'm able to run the application under GDB:

```
Thread 1 "TogglDesktop" received signal SIGSEGV, Segmentation fault.
0x00007ffff11bc9e8 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
(gdb) bt full
#0  0x00007ffff11bc9e8 in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#1  0x00007ffff11babfb in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5

[ ... trimmed ... ]

#19 0x00007fffef702df8 in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#20 0x00007ffff6a8fddb in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff74d55c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff74dca60 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00005555555a3672 in TogglApplication::notify(QObject*, QEvent*) ()
#24 0x00007ffff6a65539 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff6a68587 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff6ab9c03 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fffec02f4ae in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fffec02f748 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffec02f7e0 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6ab9213 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff6a6414b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff6a6c122 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x0000555555593e71 in main ()
```

If I install qt webengine natively (`$ sudo dnf install qt5-qtwebengine` for Fedora) and then force manually make the other Flatpak-available shared objects available, it works:

```
 /var/lib/flatpak/app/com.toggl.TogglDesktop/current/active/files$ LD_PRELOAD=./lib/libTogglDesktopLibrary.so:./lib/libOAuth2.so:./lib/libQxt.so:./lib/libBugsnag.so:./lib/libjsoncpp.so:./lib/libLua.so:./lib/libPocoDataSQLite.so:./lib/libPocoNetSSL.so:./lib/libPocoData.so:./lib/libPocoCrypto.so:./lib/libPocoNet.so:./lib/libPocoUtil.so:./lib/libPocoFoundation.so ./bin/TogglDesktop
```

With this arrangement (IE not linking against the flatpak-provided `libQt5WebEngine.so.5`, but instead linking against the native `/lib64/libQt5WebEngine.so.5`), everything works as expected — clicking "Next" on the password screen proceeds to ask about my 2fa details.

The natively installed version of qt webengine is 5.13.2. The flatpak provided version is 5.12.7. I'm unsure if the solution is in the version difference, or something missing from the flatpak-provided qt deps.

### PR DESCRIPTION
**Pull request by MartinBriza**
### 📒 Description
This PR ports our Linux app away from the custom in-house OAuth2 library (based on QtWebEngine) we used before to QtNetworkAuth.

While working on this, I found out we need to update our Linux packaging so this PR addresses just that + reintroduces compatibility with Ubuntu 16.04. That mostly consists of:
 * Using `clang-8` to build the app (instead of whatever GCC is in Ubuntu 16.04)
 * Using `jurplel/install-qt-action` to get Qt
 * Rewriting the `compose` part of `dist/linux/package.sh` to fetch dependencies more intelligently.

As a bonus, I added uploading the binaries to Artifacts so it's easier to test this.

I spent a LOOOONG time working on this so there could be some remains of something that shouldn't be there.

### 🕶️ Types of changes
- **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- Ubuntu 16.04 compatibility is back
- Google Login now uses a system browser instead of the embedded one

### 👫 Relationships
Closes #4098, #4220, probably some other ones I can't find right now

### 🔎 Review hints
I tested this on Ubuntu 16.04, 18.04, 20.04 and Fedora 32. The deb package should definitely work on all supported Ubuntu 16.04-(and newer)based distributions + probably some Debian systems as well (that's not important though because we're going to push flatpak strongly for users on those). The tarball should run on everything released since 2016, probably even before.

To test the builds from Artifacts, I suggest trying some other Ubuntu-based distro (Linux Mint is a popular one and versions newer than 18 are based on Ubuntu 16.04 and newer) to test the `deb` package and any other distro of choice for the tarball.

And of course, sorry for doing two things in one PR: Test if Google login works as expected.

As mentioned before, I spent a LOOOONG time working on this so there could be some remains of something that shouldn't be there. Please let me know if there's something odd.

### CODE REVIEW

**Comment by MartinBriza** [comment]
Can you try it again? I vaguely recall it not working for the first time sometimes, especially when the browser was started by Toggl (not running before).

**Comment by atsvirchkova** [comment]
I tried about 10 times. With opened browser and with closed, the effect still the same.

**Comment by MartinBriza** [comment]
Did you build the application yourself or used any of the packages? Is this clean Ubuntu 20.04 with GNOME that you tested on?

**Comment by atsvirchkova** [comment]
No, I didn't build myself, I used the artifacts, that you implemented in this branch. And yes, it's Ubuntu 20.04 with GNOME.

**Comment by atsvirchkova** [comment]
I checked Google sing in with my toggl google account and it works. I also checked previous release linux version 7.5.226 and the behavior is the same, works for my toggl account and doesn't work for my personal account. I still don't understand why this happens, but this thing was not introduced in you pull request @MartinBriza . So, good job!

**Pull request merged**
