### PR TITLE
Fix table view padding for Big Sur (mac)

### LINKED ISSUE #4671: Wrong table view padding on macOS Big Sur
### 💻 Environment

Platform: macOS
OS Version: macOS 11 Big Sur
Toggl Version: 7.4.283 if built on Big Sur with Xcode 12

### 🐞 Actual behavior

The table view on Big Sur has horizontal padding that's not needed. This is visible on description autocomplete and also project/tags/description dropdown. See screenshots below

### 💯 Expected behavior

Autocomplete should look the same as on Catalina macOS - without unneeded padding.

### 🔨 Steps to reproduce

Precondition:
1. macOS Big Sur 
1. Xcode 12

STR:
1. Build app with Xcode (happens only if built from Big Sur, so current stable version are okay)
2. Open any autocomplete
3. Compare with stable version

### 📦 Additional info

macOS 11 introduces three table-view styles to define different appearances that work well in specific window areas: inset, full-width, and automatic. By default it is set to `automatic` causing this behaviour ([docs](https://wiki.lazarus.freepascal.org/macOS_Big_Sur_changes_for_developers#Table_Views)):

Screenshot 2020-11-16 at 16 12 27
Screenshot 2020-11-16 at 16 12 36

### PR DESCRIPTION
**Pull request by AndrewVebster**
### 📒 Description
Set table view style for autocomplete components as `NSTableViewStyle.plain`

### 🕶️ Types of changes
- **Bug fix** (non-breaking change which fixes an issue)

### 👫 Relationships
Closes #4671

### CODE REVIEW

**Comment by AndrewVebster** [comment]
It's not building on Catalina. We can merge it only when GitHub Actions are switched to use Big Sur

**Comment by AndrewVebster** [comment]
Waiting for PR #4687 to be merged

**Comment by AndrewVebster** [comment]
Ready for review now

**Review by skel35 — APPROVED** [review]
Fixes the issue on Big Sur 👍

**Pull request merged**
