### PR TITLE
Fix ambiguous layout on Timeline for small time entries

### LINKED ISSUE #4520: Ambiguous layout error in Timeline view
### 💻 Environment
Platform: macOS
Toggl Version: 7.5.286

### 🐞 Actual behavior
Ambiguous layout error (unusable app, a purple window behind the main window)

### 💯 Expected behavior
No errors

### 🔨 Steps to reproduce
1. Open the Timeline view
2. Create 2 overlapping TEs (e.g. 10:00-10:30, 10:15-10:45)
3. Click to the left of the second TE (e.g. around 10:40).

### 📦 Additional info
image

### PR DESCRIPTION
**Pull request by AndrewVebster**
### 📒 Description

Fixes ambiguous layout when creating small time entry that overlaps with another TE. See detailed STR in related issue.

### 🕶️ Types of changes
- **Bug fix** (non-breaking change which fixes an issue)

### 👫 Relationships
Closes #4520

### 🔎 Review hints

Test if Timeline layout is not broken.

### CODE REVIEW

**Review by skel35 — CHANGES_REQUESTED** [review]
A bug was introduced:

🐞 Actual behavior
Timeline UI becomes empty. The only way to get it to work again is to restart an app.

💯 Expected behavior
Timeline UI should still function correctly.

🔨 Steps to reproduce
Create a TE 10:00 - 10:30.
Click the Timeline view at 10:45 and drag towards 10:15.

**Comment by AndrewVebster** [comment]
Cannot reproduce... is it 100% reproducible? any other specific details?

**Comment by skel35** [comment]
it's 100% reproducible for me

**Comment by AndrewVebster** [comment]
Okay, now I see. It's reproduced if edit popup is not closed before the drag event

**Comment by AndrewVebster** [comment]
And with such STR it's the same on `master`

**Comment by skel35** [comment]
you're right, I can reproduce it now on 7.5.340 -> #4570.

**Review by skel35 — APPROVED** [review]
The issue is fixed 👍

**Pull request merged**
