### PR TITLE
Click-drag to create time entry

### LINKED ISSUE #4621: Click to create time entry
### 💻 Environment
Platform: Windows

### 📒 Description
Clicking the Timeline view should create a time entry with a duration of 1hr.
The start time should correspond to the position of the cursor during the click.
The Edit view should open right after the click to allow filling in the time entry info.

### LINKED ISSUE #4622: Click-drag to create time entry
### 💻 Environment
Platform: Windows

### 📒 Description
Implement the click-drag to create a time entry in the Timeline view, same as in macOS.

Acceptance Criteria:
1. If there's very little drag (less than a few px) the default duration time entry should be created (see #4621).
2. There should be a preview of a time entry when dragging.

(moved to #4655) ~3. A separate popup to display a preview of the start time, end time, and duration of the time entry is needed. It may look like a current time entry tooltip, or it can be a separate popup altogether.~

### PR DESCRIPTION
**Pull request by atsvirchkova**
### 📒 Description
- Clicking the Timeline view (or dragging for less than 2 px) creates a time entry with a duration of 1hr.
- Clicking and dragging on Timeline view creates a TE, whose start and end corresponds to dragged distance and offset.

### 🕶️ Types of changes

 - **New feature** (non-breaking change which adds functionality)

### 👫 Relationships

Closes #4621 
Closes #4622

### CODE REVIEW

**Review by skel35 — CHANGES_REQUESTED** [review]
Crash
STR
1. Start a time entry
2. Stop a time entry

AR
ArgumentException when adding an item to a Dictionary.

**Review by skel35 — CHANGES_REQUESTED** [review]
One more huge bug:
Hovering over a running time entry does not show a tooltip.
Clicking over a running time entry creates a new time entry (?) instead of opening the Edit view.

**Comment by atsvirchkova** [comment]
Thank you for good testing. I really missed a couple of things after rebase. Fixed now.

**Review by skel35 — CHANGES_REQUESTED** [review]
The code looks fine.

Issues:
1. Acceptance Criteria 3 in #4622 is not implemented. Let me know if you want to create a separate issue for it.
2. The Edit view should not open before the click/click-drag is finished.

**Comment by atsvirchkova** [comment]
@skel35 Let's move the Acceptance criteria 3 to the separate issue.

**Comment by skel35** [comment]
> @skel35 Let's move the Acceptance criteria 3 to the separate issue.

done #4665

**Comment by atsvirchkova** [comment]
Thank you. Fixed the issue with edit view.

**Comment by skel35** [comment]
@atsvirchkova sometimes the created time entry turns out to be very small, ~1 min long, regardless of how much was dragged. Is this going to be fixed in scope of #4563?

**Comment by atsvirchkova** [comment]
@skel35 yes, you can already test how it's working in #4662 . This PR includes drag to create changes.

**Review by skel35 — APPROVED** [review]
Looks good, other than issues which are going to be fixed separately (#4665, #4563)

**Pull request merged**
