### PR TITLE
[WIP] Online Client Test

### PR DESCRIPTION
**Pull request by MartinBriza**
### 📒 Description
This is a test that tries to emulate a full Toggl client using our library.
More description TBD

### 🕶️ Types of changes
- **New feature**

### 🔎 Review hints
No review hints, yet.
I'd love some hints about what and how to test.

### CODE REVIEW

**Comment by MartinBriza** [comment]
First few comments are taken from the `fix/library-overhaul/00-fix-tests` branch

**Comment by MartinBriza** [comment]
I got bored with the load of conflicts so I squashed the patch into just one commit over current `master`. This is now possible to merge. Since it's just a test, it's safe to merge, no breakage is going to occur.

It is testable if you have `"../../../toggldesktop/src/ssl/cacert.pem"` accessible at this precise path (ugh). This will get fixed in a later revision of the test.

**Comment by skel35** [comment]
@MartinBriza  I'm getting this:
>~/Documents/toggldesktop/toggldesktop/build $ ../dist/run-tests.sh test=./src/test/TogglOnlineTest name="App"
Running main() from gtest_main.cc
[==========] Running 23 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from Base
[ RUN      ] Base.Initialize
Will test with the following credentials:
Username: hiIO1x3EVxG38qMz@toggldesktop-test.com
Password: F4yqvt1VMgBorCTX
unknown file: Failure
C++ exception with description "File not found" thrown in the test body.
[  FAILED  ] Base.Initialize (210 ms)
[ RUN      ] Base.GetCountries
../dist/run-tests.sh: line 71:  5594 Segmentation fault      (core dumped) $test --gtest_output=xml:${name}_result.xml
Test results were not reported because we're not in master
Current ref is: 
rm: cannot remove 'App_result.xml': No such file or directory

I think I have `cacert.pem` file in the correct directory, not sure though.
How do you run these tests locally?

I can still merge it, of course, since it doesn't affect anything yet, but it'd be nice to get it working if it works on your side.

**Comment by MartinBriza** [comment]
I have my build folder next to the source directory. If you have the build directory inside the toggldesktop root, I didn't test it with the test runner script at all. The gist is you need to have `../../../toggldesktop/src/ssl/cacert.pem` accessible from your `$PWD`

**Comment by skel35** [comment]
I rebuilt the app with build folder next to the source folder and am still getting the same result

**Comment by MartinBriza** [comment]
Again, it really depends on where you run the app from. If the cacert file is accessible from your current working directory, it should work.

**Pull request merged**
